### ISSUE TITLE
Cannot open Kitty

### ISSUE THREAD

**Issue by massivebird** [massivebird/dotfiles#12]
> [!NOTE]
> I still have TTYs and a graphical terminal that I can work with in the meantime :3

After a `sudo nixos-rebuild switch --flake ~/.config/nix#`, Kitty refuses to launch from any source. Trying to launch it from the terminal produces the following error:

```
$ kitty
[310 17:57:59.910894] [glfw error 65542]: EGL: Failed to get EGL display: Success
[310 17:57:59.914151] Traceback (most recent call last):
  File "/nix/store/pgg0i24wi8zy5zc0gvbl9asd8q5zv0ki-kitty-0.28.1/bin/../lib/kitty/kitty/main.py", line 531, in main
    _main()
  File "/nix/store/pgg0i24wi8zy5zc0gvbl9asd8q5zv0ki-kitty-0.28.1/bin/../lib/kitty/kitty/main.py", line 523, in _main
    run_app(opts, cli_opts, bad_lines)
  File "/nix/store/pgg0i24wi8zy5zc0gvbl9asd8q5zv0ki-kitty-0.28.1/bin/../lib/kitty/kitty/main.py", line 275, in __call__
    _run_app(opts, args, bad_lines)
  File "/nix/store/pgg0i24wi8zy5zc0gvbl9asd8q5zv0ki-kitty-0.28.1/bin/../lib/kitty/kitty/main.py", line 248, in _run_app
    window_id = create_os_window(
ValueError: Failed to create GLFWwindow
```

## Metadata

Running `nix-shell -p nix-info --run "nix-info -m"` produces the following:

```
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.60, NixOS, 23.11 (Tapir), 23.11.20231104.85f1ba3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(penguino): `""`
 - channels(root): `"home-manager, nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by massivebird** [comment]
Maybe unrelated: Kitty's [nixpkgs unstable](https://repology.org/project/kitty/versions) release says it's 0.30.1, but mine is older:

```
$ kitty --version
kitty 0.28.1 created by Kovid Goyal
```

The [NixOS Packages](https://search.nixos.org/packages?channel=unstable&show=kitty&from=0&size=50&sort=relevance&type=packages&query=kitty) site also lists it as 0.30.1, so why is mine not 0.30.1??

**Comment by massivebird** [comment]
`git checkout bfa5f15` is the latest commit that works. Running `nixos-rebuild` on any commit thereafter doesn't work:

```nix
$ git checkout c5d2fb7; nor --option eval-cache false
Previous HEAD position was 303f0de fixes: package and font errors
HEAD is now at c5d2fb7 nix/flake.lock: Update
building the system configuration...
trace: warning: The option `fonts.fonts' defined in `/nix/store/58mb8r44jrlafva99zksygfns5hxdpia-source/nix/modules/common' has been renamed to `fonts.packages'.
trace: warning: The option `fonts.enableDefaultFonts' defined in `/nix/store/58mb8r44jrlafva99zksygfns5hxdpia-source/nix/modules/common' has been renamed to `fonts.enableDefaultPackages'.
error:
       … while calling the 'head' builtin

         at /nix/store/z6w242l49pbrdawkz5vdhfxh2mvsj36c-source/lib/attrsets.nix:850:11:

          849|         || pred here (elemAt values 1) (head values) then
          850|           head values
             |           ^
          851|         else

       … while evaluating the attribute 'value'

         at /nix/store/z6w242l49pbrdawkz5vdhfxh2mvsj36c-source/lib/modules.nix:807:9:

          806|     in warnDeprecation opt //
          807|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          808|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: 'exa' has been removed because it is unmaintained upstream. Consider using 'eza', a maintained fork
```

**Comment by massivebird** [comment]
I ran a `nix flake update --commit-lock-file ~/.config/nix/#` to update the lock file AGAIN (I think this all broke after it updated), and it APPEARS to be working U3U

I have no idea what changed!

**Comment by massivebird** [comment]
It is SO NOT OVER :sob: it's back again. wtf is happening

this is a good time to note that this issue happens when I do `sudo nixos-rebuild switch --flake ~/.config/nix#` and receive the following GIANT output (which has never happened before):

```
building the system configuration...
stopping the following units: NetworkManager-wait-online.service, NetworkManager.service, alsa-store.service, audit.service, avahi-daemon.service, avahi-daemon.socket, bluetooth.service, cpufreq.service, cups-browsed.service, cups.service,cups.socket, kmod-static-nodes.service, logrotate-checkconf.service, mount-pstore.service, network-local-commands.service, network-setup.service, nscd.service, power-profiles-daemon.service, resolvconf.service, rtkit-daemon.service, systemd-modules-load.service, systemd-oomd.service, systemd-oomd.socket, systemd-sysctl.service, systemd-timesyncd.service, systemd-tmpfiles-setup-dev.service, systemd-udevd-control.socket, systemd-udevd-kernel.socket, systemd-udevd.service, wpa_supplicant.service
NOT restarting the following changed units: getty@tty1.service, systemd-backlight@backlight:intel_backlight.service, systemd-fsck@dev-disk-by\x2duuid-66BD\x2d1ACE.service, systemd-journal-flush.service, systemd-logind.service, systemd-random-seed.service, systemd-remount-fs.service, systemd-tmpfiles-setup.service, systemd-update-utmp.service, systemd-user-sessions.service, user-runtime-dir@1000.service, user@1000.service
activating the configuration...
setting up /etc...
removing obsolete symlink ‘/etc/libblockdev/conf.d/00-default.cfg’...
removing obsolete symlink ‘/etc/libblockdev/conf.d/10-lvm-dbus.cfg’...
restarting systemd...
reloading user units for penguino...
setting up tmpfiles
reloading the following units: dbus.service, firewall.service, reload-systemd-vconsole-setup.service
restarting the following units: dev-hugepages.mount, nix-daemon.service, polkit.service, sshd.service, systemd-journald.service
starting the following units: NetworkManager-wait-online.service, NetworkManager.service, alsa-store.service, audit.service, avahi-daemon.socket, bluetooth.service, cpufreq.service, cups-browsed.service, cups.socket, kmod-static-nodes.service, logrotate-checkconf.service, mount-pstore.service, network-local-commands.service, network-setup.service, nscd.service, power-profiles-daemon.service, resolvconf.service, rtkit-daemon.service, systemd-modules-load.service, systemd-oomd.socket, systemd-sysctl.service, systemd-timesyncd.service, systemd-tmpfiles-setup-dev.service, systemd-udevd-control.socket, systemd-udevd-kernel.socket, wpa_supplicant.service
the following new units were started: NetworkManager-dispatcher.service, systemd-hostnamed.service, systemd-tmpfiles-setup-dev-early.service, systemd-vconsole-setup.service
```

**Comment by massivebird** [comment]
Doing this WORKS:

```bash
$ nix-shell -p kitty
# now in nix shell
$ kitty --version
kitty 0.30.1 created by Kovid Goyal
$ kitty
```

so _why isn't my flake downloading the latest version of Kitty?_

**Comment by massivebird** [comment]
I don't know. It's fixed now. I don't know
