### ISSUE TITLE
bug: unable to use wgpu and other [Rust] graphic frameworks

### ISSUE THREAD

**Issue by massivebird** [massivebird/dotfiles#8]
Trying to run [wgpu](https://github.com/gfx-rs/wgpu) examples yields an error like:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os(OsError { line: 81, file: "/home/penguino/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.3/src/platform_impl/linux/wayland/event_loop/mod.rs", error: WaylandError(Connection(NoWaylandLib)) })', /home/penguino/p-rs/wgpu/examples/common/src/framework.rs:97:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This seems like a Nix config/package issue :chicken:

**Comment by massivebird** [comment]
updated stack trace:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os(OsError { line: 81, file: "/home/penguino/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.3/src/platform_impl/linux/wayland/event_loop/mod.rs", error: WaylandError(Connection(NoWaylandLib)) })', /home/penguino/p-rs/wgpu/examples/common/src/framework.rs:97:39
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::unwrap
             at /build/rustc-1.72.1-src/library/core/src/result.rs:1076:23
   4: wgpu_example::framework::setup::{{closure}}
             at ./examples/common/src/framework.rs:97:22
   5: pollster::block_on
             at /home/penguino/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pollster-0.3.0/src/lib.rs:128:15
   6: wgpu_example::framework::run
             at ./examples/common/src/framework.rs:398:17
   7: boids::main
             at ./examples/boids/src/main.rs:325:5
   8: core::ops::function::FnOnce::call_once
             at /build/rustc-1.72.1-src/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by massivebird** [comment]
Trying to run a `pixels` example:

```
$ WINIT_UNIX_BACKEND=wayland cargo run --release --package conway
warning: /home/penguino/p-rs/pixels/examples/minimal-winit-android/Cargo.toml: `crate_type` is deprecated in favor of `crate-type` and will not work in the 2024 edition
(in the `minimal_winit_android` library target)
    Finished `release` profile [optimized] target(s) in 0.09s
     Running `/home/penguino/p-rs/pixels/target/release/conway`
thread 'main' panicked at /home/penguino/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/linux/mod.rs:730:26:
Failed to initialize Wayland backend: NoWaylandLib
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by massivebird** [comment]
wgpu HAS added a `shell.nix` file to the repo, but I can't tell if the examples are running correctly on my laptop. Which probably means they aren't.

**Comment by massivebird** [comment]
OK so the following flake makes (most) of the `pixels` examples work:

```nix
{
  description = "idk";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    naersk = {
      url = "github:nix-community/naersk/master";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils, naersk, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
        naersk-lib = pkgs.callPackage naersk { };
        libPath = with pkgs; lib.makeLibraryPath [
          libGL
          libxkbcommon
          wayland
        ];
      in
        with pkgs;
      {
        packages.default = naersk-lib.buildPackage ./.;

        # for `nix develop`:
        devShell = with pkgs;
          mkShell {
            buildInputs = [
              atk
              cargo
              fontconfig
              gdk-pixbuf
              glib
              libudev-zero
              pango
              pkg-config
              rubyPackages_3_1.gdk3
              rust-analyzer
              rustc
            ];

            RUST_LOG = "debug";
            RUST_SRC_PATH = "${pkgs.rust.packages.stable.rustPlatform.rustLibSrc}";
            LD_LIBRARY_PATH = libPath;
            WINIT_UNIX_BACKEND = "wayland";
          };
      }
    );
}
```
